BDE_HEADER = [(0, 3, "Boot entry point"),
              (3, 8, "File system signature"),
              (11, 2, "Bytes per sector"),
              (13, 1, "Sectors per cluster block"),
              (14, 2, "Reserved Sectors"),
              (16, 1, "Number of File Allocation Tables (FATs)"),
              (17, 2, "Root directory entries"),
              (19, 2, "Total number of sectors (16-bit)"),
              (21, 1, "Media descriptor"),
              (22, 2, "Sectors Per File Allocation Table (FAT)"),
              (24, 2, "Sectors per track"),
              (26, 2, "Number of heads"),
              (28, 4, "Number of hidden sectors"),
              (32, 4, "Total number of sectors (32-bit)"),
              (36, 4, "Sectors per file allocation table"),
              (40, 2, "FAT Flags"),
              (42, 2, "Version (Defined as 0)"),
              (44, 4, "Cluster number of root directory start"),
              (48, 2, "Sector number of FS Information Sector"),
              (50, 2, "Sector number of a copy of this boot sector (0 if no backup copy exists)"),
              (52, 12, "Reserved"),
              (64, 1, "Physical Drive Number"),
              (65, 1, "Reserved"),
              (66, 1, "Extended boot signature"),
              (67, 4, "Volume serial number"),
              (71, 11, "Volume label"),
              (82, 8, "File system signature"),
              (90, 70, "Bootcode"),
              (160, 16, "BitLocker identifier (GUID)"),
              (176, 8, "FVE metadata block 1 offset"),
              (184, 8, "FVE metadata block 2 offset"),
              (192, 8, "FVE metadata block 3 offset"),
              (200, 307, "Unknown (part of bootcode)"),
              (507, 3, "Unknown"),
              (510, 2, "Sector signature")]


FVE_METADATA_BLOCK_HEADER = [(0, 8, "Signature"),
                             (8, 2, "Size"),
                             (10, 2, "Version"),
                             (12, 2, "Unknown"),
                             (14, 2, "Unknown copy"),
                             (16, 8, "Encrypted volume size (bytes)"),
                             (24, 4, "Unknown"),
                             (28, 4, "Number of volume header sectors"),
                             (32, 8, "FVE metadata block 1 offset"),
                             (40, 8, "FVE metadata block 2 offset"),
                             (48, 8, "FVE metadata block 3 offset"),
                             (56, 8, "Volume header offset")]


FVE_METADATA_HEADER = [(0, 4, "Metadata size"),
                       (4, 4, "Version"),
                       (8, 4, "Metadata header size"),
                       (12, 4, "Metadata size copy"),
                       (16, 16, "Volume identifier (GUID)"),
                       (32, 4, "Next nonce counter"),
                       (36, 4, "Encryption method"),
                       (40, 8, "Creation time (FILETIME)")]


FVE_METADATA_ENTRY = [(0, 2, "Entry size"),
                      (2, 2, "Entry type"),
                      (4, 2, "Value type"),
                      (6, 2, "Version")]
